name: mkdocs verify
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Verify that docs can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0.9.0
        with:
          mkdocs_version: 'latest'
          requirements: 'requirements.txt'
          configfile: 'mkdocs.yml'
